#!/bin/bash
printf %s '# :student: :lock: University Repository
## Program: Applied Mathematics and Computer Science
## :evergreen_tree: Structure:
```bash' > README.md
tree --dirsfirst --noreport -L 3 >> README.md
printf %s '```' >> README.md
